title: Engineer notes
description: My Personal notes
author: Alexey Shurov
github: https://github.com/a73xsh
about: I'm an infrastructure engineer, especially on virtualization.
disqus_shortname: engineer-notes
google_analytics: UA-73904067-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#   - icon: fa-facebook
#     link: "#"
#   - icon: fa-twitter
#     link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/al3xsh/"
#   - icon: fa-stack-exchange
#     link: "#"
    - icon: fa-certificate
      link: "https://www.youracclaim.com/users/alexey-shurov/badges"
    - icon: fa-github
      link: "https://github.com/a73xsh"
    - icon: fa-envelope
      link: mailto:alexey@shurov.pro

#share:
#  twitter_username: github.io
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/
    - text: XML Feed
      url: /feed.xml

url: "https://a73xsh.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
